version: "3"

services:
  ####################### Client Definition #######################
  client:
    image: client:${GIT_COMMIT:-latest}
    container_name: client
    build:
      context: client
    command: ["npm", "run", "serve"]
    environment:
      HOST: 0.0.0.0
      PORT: 3000
    ports:
      - 3000:3000
    networks:
      - default

  ####################### Database Definition #######################
  database:
    image: database:${GIT_COMMIT:-latest}
    container_name: database
    build:
      context: database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sample_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - default

  ####################### Server Definition #######################
  server:
    restart: on-failure
    image: server:${GIT_COMMIT:-latest}
    container_name: server
    build:
      context: server
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgres://admin:password@database:5432/sample_db
      - DATABASE_TEST_URL=postgres://admin:password@database:5432/sample_db_test
      - SMTP_USERNAME=${SMTP_USERNAME:-user}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-pass}
    depends_on:
      - server-migrate
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/foo"]
      interval: 1s
      timeout: 10s
      retries: 30

  ####### Server Database Migration Definition ###########

  server-migrate:
    restart: on-failure
    image: server-migrate:${GIT_COMMIT:-latest}
    container_name: server-migrate
    build:
      context: server
    command: python manage.py create-db
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgres://admin:password@database:5432/sample_db
      - DATABASE_TEST_URL=postgres://admin:password@database:5432/sample_db_test
    depends_on:
      - database
    networks:
      - default

####################### Networks Definition #######################
networks:
  default:
    driver: bridge

####################### Volumes Definition #######################
volumes:
  postgres-data:
