version: "3"

services:
  ####################### Client Definition #######################
  client:
    restart: always
    container_name: client
    build:
      context: client
    command: ["npm", "run", "serve"]
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      API_URL: http://localhost:5000/api
    volumes:
      - "./client:/opt/client"
      - "/opt/client/node_modules"
    ports:
      - 3000:3000
    depends_on:
      - server
    networks:
      - default

  ####################### Database Definition #######################
  database:
    container_name: database
    image: centos/postgresql-10-centos7:latest
    ports:
      - 5435:5432
    environment:
      - POSTGRESQL_USER=admin
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=sample_db
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    networks:
      - default

  ####################### Server Definition #######################
  server:
    container_name: server
    build:
      context: server
    volumes:
      - "./server:/opt/server/"
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=app.config.DevelopmentConfig
      - POSTGRESQL_USER=admin
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=sample_db
      - POSTGRESQL_SERVICE=database
    depends_on:
      - server-migrate
    networks:
      - default

  ####### Server Database Migration Definition ###########
  server-migrate:
    restart: on-failure
    container_name: server-migrate
    build:
      context: server
    command: flask db upgrade
    volumes:
      - "./server:/opt/server/"
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=app.config.Config
      - DATABASE_URL=postgres://admin:password@database:5432/sample_db
    depends_on:
      - database
    networks:
      - default

####################### Networks Definition #######################
networks:
  default:
    driver: bridge

####################### Volumes Definition #######################
volumes:
  postgres-data:
