version: "3"

services:
  ####################### Client Definition #######################
  client:
    image: client:${GIT_COMMIT:-latest}
    container_name: client
    build:
      context: client
    command: ["npm", "run", "start"]
    environment:
      HOST: 0.0.0.0
      PORT: 3000
    volumes:
      - ./client/src/:/opt/client/src/
      - "/app/node_modules"
    ports:
      - 80:3000
    networks:
      - default

  ####################### Database Definition #######################
  database:
    image: database:${GIT_COMMIT:-latest}
    container_name: database
    build:
      context: database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - default

  ####################### Server Definition #######################
  server:
    image: server:${GIT_COMMIT:-latest}
    container_name: server
    build:
      context: server
    volumes:
      - "./server:/opt/server/"
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgres://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-password}@database:5432/postgres
      - DATABASE_TEST_URL=postgres://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-password}@database:5432/postgres_test
      - SMTP_USERNAME=${SMTP_USERNAME:-user}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-pass}
      - SMTP_ENABLE=${SMTP_ENABLE:-True}
    depends_on:
      - server-migrate
    networks:
      - default

  ####### Server Database Migration Definition ###########

  server-migrate:
    restart: on-failure
    image: server-migrate:${GIT_COMMIT:-latest}
    container_name: server-migrate
    build:
      context: server
    command: python manage.py create-db
    volumes:
      - "./server:/opt/server/"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgres://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-password}@database:5432/postgres
      - DATABASE_TEST_URL=postgres://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-password}@database:5432/postgres_test
    depends_on:
      - database
    networks:
      - default

####################### Networks Definition #######################
networks:
  default:
    driver: bridge

####################### Volumes Definition #######################
volumes:
  postgres-data:
