"""Create foo table and seed

Revision ID: 25461d5f0f77
Revises: 
Create Date: 2020-02-03 22:52:44.208185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25461d5f0f77'
down_revision = None
branch_labels = None
depends_on = None

# seed foo table with sample
def seed_data(table):
    op.bulk_insert(
        table,
        [
            {'string_field': 'Hello World'},
        ]
    )

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    table = op.create_table('foo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('string_field', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # seed some data
    seed_data(table)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('foo')
    # ### end Alembic commands ###
