name: Continuous Integration

on: pull_request

jobs:
  test:
    name: Run client and server tests...
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run client tests
        run: make client-test

# TODO: Add server tests
#      - name: Run server tests
#        run: make server-test
