name: Continuous Integration

on: pull_request

jobs:
  test:
    name: Run client and server tests...
    runs-on: ubuntu-latest
    steps:
      - name: Test OpenShift CLI download
        run: |
          pwd
          ls -a
          wget -O oc.tar.gz https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
          FILE=$(tar --warning=no-unknown-keyword -tf oc.tar.gz | grep '/oc$')
          tar --warning=no-unknown-keyword -zxf oc.tar.gz "$FILE"
          sudo cp "$FILE" /usr/local/bin/oc
      
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Test OpenShift CLI version
        run: |
          ls
          oc version

#       - name: Run client tests
#         run: make client-test

# TODO: Add server tests
#      - name: Run server tests
#        run: make server-test
