name: Continuous Deployment

on:
  push:
    branches:
#      - develop
      - BOIL-36-github-actions

jobs:
  test:
    name: Run client and server tests...
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run client tests
        run: make client-test

# TODO: Add server tests
#      - name: Run server tests
#        run: make server-test

  deploy:
    name: Build and deploy client, database and server...
    runs-on: ubuntu-latest

    # Env variables get injected into make scripts.
    # `secrets.*` come from the GitHub repository settings.
#    env:
#      OPENSHIFT_AUTH_TOKEN: ${{ secrets.OPENSHIFT_AUTH_TOKEN }}

    steps:
      - name: Download OpenShift CLI
        run: |
          wget --quiet -O oc.tar.gz https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
          FILE=$(tar --warning=no-unknown-keyword -tf oc.tar.gz | grep '/oc$')
          tar --warning=no-unknown-keyword -zxf oc.tar.gz "$FILE"
          sudo mv "$FILE" /usr/local/bin/oc

      - name: Login to Openshift
        run: |
          echo {{ secrets.OPENSHIFT_AUTH_TOKEN }}
          oc login https://console.pathfinder.gov.bc.ca:8443 --token={{ secrets.OPENSHIFT_AUTH_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v1

      - name: Deploy database
        run: make deploy-database NAMESPACE=apdwlc-dev APP_NAME=openshift-launchpad POSTGRESQL_DATABASE=launchpad

#      - name: Deploy server
#        run: make deploy-server NAMESPACE=apdwlc-dev APP_NAME=openshift-launchpad REPO=https://github.com/bcgov/openshift-launchpad BRANCH=BOIL-36-github-actions

#      - name: Deploy client
#        run: make deploy-client NAMESPACE=apdwlc-dev APP_NAME=openshift-launchpad REPO=https://github.com/bcgov/openshift-launchpad BRANCH=BOIL-36-github-actions API_URL=http://openshift-launchpad-server-launchpad.192.168.64.4.nip.io
