name: Continuous Integration

on: pull_request

jobs:
  test:
    name: Run client and server tests...
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Test OpenShift CLI download
        run: |
          wget -O oc.tar.gz https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
          tar -zxf oc.tar.gz openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit/oc
          mv oc /usr/local/bin
        
      - name: Test OpenShift CLI version
        run: oc version

#       - name: Run client tests
#         run: make client-test

# TODO: Add server tests
#      - name: Run server tests
#        run: make server-test
