name: Continuous Deployment

on:
  push:
    branches:
      - develop

jobs:
  test:
    name: Run client and server tests...
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run client tests
        run: make client-test

# TODO: Add server tests
#      - name: Run server tests
#        run: make server-test

# TODO: Add Openshift login script
#  deploy:
#    name: Build and deploy client, database and server...
#    runs-on: ubuntu-latest
#
#    # Env variables get injected into make scripts.
#    # `secrets.*` come from the GitHub repository settings.
#    env:
#      MY_SECRET: ${{ secrets.MY_SECRET }}
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v1
#
#      - name: Login to Openshift
#        run: make login-openshift
#
#      - name: Deploy client
#        run: make deploy-client
#
#      - name: Deploy database
#        run: make deploy-database
#
#      - name: Deploy server
#        run: make deploy-server
