name: Continuous Integration

on: pull_request

jobs:
  deploy:
    name: Create new instance of client, database and server...
    runs-on: ubuntu-latest

    steps:
      - name: Set env variables
        run: |
          echo ::set-env name=APP_NAME::"openshift-launchpad-PR$(echo $GITHUB_REF | sed 's/.*pull\/\([0-9]*\)\/.*/\1/')"
          echo ::set-env name=NAMESPACE::"apdwlc-tools"
          echo ::set-env name=POSTGRESQL_DATABASE::"launchpad"
          echo ::set-env name=REPO::"https://github.com/bcgov/openshift-launchpad"
          echo ::set-env name=BRANCH::"BOIL-36-github-actions"

      - name: Set API env
        run: echo ::set-env name=API_URL::"http://$APP_NAME-server-$NAMESPACE.pathfinder.gov.bc.ca"

      - name: Download OpenShift CLI
        run: |
          wget --quiet -O oc.tar.gz https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
          FILE=$(tar --warning=no-unknown-keyword -tf oc.tar.gz | grep '/oc$')
          tar --warning=no-unknown-keyword -zxf oc.tar.gz "$FILE"
          sudo mv "$FILE" /usr/local/bin/oc

      - name: Login to Openshift
        run: oc login https://console.pathfinder.gov.bc.ca:8443 --token=${{ secrets.OPENSHIFT_AUTH_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v1

      - name: Create Network Security Policy
        run: |
          make create-nsp NAMESPACE=$NAMESPACE APP_NAME=$APP_NAME
          sleep 30s

      - name: Create database
        run: make create-database NAMESPACE=$NAMESPACE APP_NAME=$APP_NAME POSTGRESQL_DATABASE=$POSTGRESQL_DATABASE

      - name: Create server
        run: make create-server NAMESPACE=$NAMESPACE APP_NAME=$APP_NAME REPO=$REPO BRANCH=$BRANCH

      - name: Create client
        run: make create-client NAMESPACE=$NAMESPACE APP_NAME=$APP_NAME REPO=$REPO BRANCH=$BRANCH API_URL=$API_URL