name: Continuous Integration

on: pull_request

jobs:
  deploy:
    name: Create new instance of client, database and server...
    runs-on: ubuntu-latest

    env:
#      PR_NUMBER: ${{ $GITHUB_REF | sed 's/.*pull\/\([0-9]*\)\/.*/\1/' }}
      NAMESPACE: apdwlc-tools
      APP_NAME: openshift-launchpad-PR#$PR_NUMBER
      POSTGRESQL_DATABASE: launchpad
      REPO: https://github.com/bcgov/openshift-launchpad
      BRANCH: BOIL-36-github-actions
      API_URL: http://$APP_NAME-server-$NAMESPACE.pathfinder.gov.bc.ca

    steps:
#      - name: Set PR Number env variable
#        run: |
#          export PR_NUMBER=$(echo $GITHUB_REF | sed 's/.*pull\/\([0-9]*\)\/.*/\1/')
#          export NAMESPACE="apdwlc-tools"
#          export APP_NAME="openshift-launchpad-PR#$PR_NUMBER"
#          export POSTGRESQL_DATABASE="launchpad"
#          export REPO="https://github.com/bcgov/openshift-launchpad"
#          export BRANCH="BOIL-36-github-actions"
#          export API_URL="http://$APP_NAME-server-$NAMESPACE.pathfinder.gov.bc.ca"
#
      - name: Testing
        run: |
          echo ::set-env name=FOO::$(echo -n "hello world")
          echo "$FOO"
#          echo "$PR_NUMBER"
#          echo "$NAMESPACE"
#
#      - name: Download OpenShift CLI
#        run: |
#          wget --quiet -O oc.tar.gz https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
#          FILE=$(tar --warning=no-unknown-keyword -tf oc.tar.gz | grep '/oc$')
#          tar --warning=no-unknown-keyword -zxf oc.tar.gz "$FILE"
#          sudo mv "$FILE" /usr/local/bin/oc
#
#      - name: Login to Openshift
#        run: oc login https://console.pathfinder.gov.bc.ca:8443 --token=${{ secrets.OPENSHIFT_AUTH_TOKEN }}
#
#      - name: Checkout
#        uses: actions/checkout@v1
#
#      - name: Create Network Security Policy
#        run: |
#          make create-nsp NAMESPACE="$NAMESPACE" APP_NAME="$APP_NAME"
#          sleep 30s
#
#      - name: Create database
#        run: make create-database NAMESPACE="$NAMESPACE" APP_NAME="$APP_NAME" POSTGRESQL_DATABASE=$POSTGRESQL_DATABASE
#
#      - name: Create server
#        run: make create-server NAMESPACE="$NAMESPACE" APP_NAME="$APP_NAME" REPO=$REPO BRANCH=$BRANCH
#
#      - name: Create client
#        run: make create-client NAMESPACE="$NAMESPACE" APP_NAME="$APP_NAME" REPO=$REPO BRANCH=$BRANCH API_URL=$API_URL